pip install django
pip install django-ace
pip install psycopg2
pip install pytz
pip install SQLAlchemy
python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic
python manage.py createsuperuser
python manage.py runserver